-- postgresql
create table if not exists arrangementer (
  id bigint generated by default as identity primary key,
  navn text,
  dirigent text,
  starttid timestamp,
  pameldingsfrist timestamp,
  letsreg_id integer unique,
  letsreg_etterpamelding_id integer unique
);

create table if not exists deltakere (
  id bigint generated by default as identity primary key,
  arrangement_id integer not null references arrangementer(id),
  letsreg_id integer not null unique,
  letsreg_ordre_id integer not null,
  fornavn text not null,
  etternavn text not null,
  epostadresse text not null,
  telefonnummer text not null,
  instrument text not null,
  annen_info text,
  opprettet timestamp default current_timestamp,
  oppdatert timestamp default current_timestamp,
  noter_sendt_ut timestamp
);
